#!/usr/bin/python
import crimeclassifier
from sys import exit
from sys import argv

help_ = """
HOW TO USE IT:

    python crimeclassifier.py OPERATION

OPERATION:
    genReport dataset_filename
    genBin report config
    classify dataset_filename

Notes:
    report and config are json files generated by
    this package.

    dataset_filename in genReport can be a csv
    file or a zip with the csv inside. In classify
    have to be the zip file generated by this library.
"""


def main():
    if len(argv) < 2:
        print(help_)
        return -1
    elif argv[1] == "genReport" and len(argv) == 3:
        crimeclassifier.create_report(argv[2])
        return 0
    elif argv[1] == "genBin" and len(argv) == 4:
        crimeclassifier.to_bin(argv[2], argv[3])
        return 0
    elif argv[1] == "classify" and len(argv) == 3:
        crimeclassifier.classify(argv[2])
        return 0
    else:
        print(help_)
        return -1


if __name__ == '__main__':
    exit(main())
